spring:

  application:
    name: cash-lens

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

gemini:
  api-key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL:gemini-3.6-flash}
  multimodal-model: ${GEMINI_MODEL:gemini-3.6-flash}
